spring:
  h2:
    console:
      path: /h2-console
      enabled: true

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      show-sql: true

  liquibase:
    enabled: true
    change-log: classpath:changelog/changelog-master.xml


#  datasource:
#    url: jdbc:postgresql://ec2-54-247-70-127.eu-west-1.compute.amazonaws.com:5432/dmohrj0k6s4s7
#    driverClassName: org.postgresql.Driver
#    username: peqksetenpjnog
#    password: 4cc0413eb0a3147923e909b71453de08a278420e3184566d11e6ae5c8e53c1c0
#  jpa:
#    hibernate:
#      ddl-auto: none
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#    properties:
#      hibernate:
#        jdbc:
#          lob:
#            non_contextual_creation: true
#        dialect: org.hibernate.dialect.PostgreSQL9Dialect
#        id:
#          new_generator_mappings: true
#    show-sql: true
#    database-platform: org.hibernate.dialect.PostgreSQL9Dialect