spring:
  h2:
    console:
      path: /h2-console
      enabled: true

#  datasource:
#    url: jdbc:postgresql://ec2-54-75-230-253.eu-west-1.compute.amazonaws.com:5432/d9cs197n8jhccj
#    driverClassName: org.postgresql.Driver
#    username: kbinuqexfaergr
#    password: 4daab37ba1fec6418d2e5d36ab515c63b2057a9b28d46162cc467a44c7fa58b7
#  jpa:
#    hibernate:
#      ddl-auto: none
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#    properties:
#      hibernate:
#        jdbc:
#          lob:
#            non_contextual_creation: true
#        dialect: org.hibernate.dialect.PostgreSQL9Dialect
#        id:
#          new_generator_mappings: true
#    show-sql: true
#    database-platform: org.hibernate.dialect.PostgreSQL9Dialect